### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by wangnanv5** [Liang-ZX/OAI-registration#1]
<img width="903" alt="2ae6e54a9ce0c269c8e62212c7426e0" src="https://github.com/Liang-ZX/OAI-registration/assets/62439985/b7cf6bb1-a53e-4d5c-b2ba-f135ebe5d33f">
hello，the dataset was so big，can you provide this dataset by nii？thank U！

**Comment by Liang-ZX** [comment]
Hello, we also download it from nih [website](https://nda.nih.gov/oai). I suggest to use official source data. Thank you.
